### ISSUE TITLE
Using Flow with Javascript

### ISSUE THREAD

**Issue by marvinchin** [nus-cs3281/2019#17]

**Comment by damithc** [comment]
Slides? Description?

**Comment by marvinchin** [comment]
**WIIFY**
Write more robust Javascript code with Flow

**Key Points**
- Flow improves correctness of your code
- Flow increases development velocity
- Flow is easy to integrate into your application

**Impact**
Understand the importance of introducing static typing to Javascript, and consider adopting Flow in Javascript projects

**Slides**
https://docs.google.com/presentation/d/1VjUe5cBWRVBYjoM7t-lZ8Vlcj7StiKXbzDjrhSN06cs/edit?usp=sharing
