### ISSUE TITLE
Is functional programming really hard?

### ISSUE THREAD

**Issue by junming403** [nus-cs3281/2019#33]
Why functional programming and why it matters?

**Comment by damithc** [comment]
Need to update with more info (key points etc.)
Upload slides too.

**Comment by junming403** [comment]
<h2>PUNCH</h2>
Functional programming is always considered abstract and hard to understand while today I hope to give you a new sense of what is functional programming.

<h2>WIIFY</h2>
Even though you do not want to be a functional programmer, there are a lot of good practices and concepts you can learn from functional programming.

<h2>Roadmap</h2>
1.  Functional programming think in terms of the mapping relation between data instead of how to mutating the data.
2. Functional programming require most of the functions to have no side effects. 
3. Functions with no side effects implies referential transparency. 

<h2> Key points</h2>
1. Function with no side effects are easier to test. 
2. Implementing programs with a pure core and a thin layer on the outside that handles side effects makes our program more testable and more intuitive. 
3. Referential transparency helps us reasoning and debug our program.

<h2>Impact </h2>
Know: functional programming is not hard as you heard, there are a lot of good practices worth learning even though you do not want to be a functional programmer. 
Believe: functional programming is worth learning.
Do/Call to Action: start learning/ exploring functional programming.

Slides in pdf:
[FP_junming.pdf](https://github.com/nus-cs3281/2019/files/2836544/FP_junming.pdf)
